import { z } from 'zod';
import { isValidDateId } from './dates';
import { MAX_DURATION_MIN, MAX_GRAMS_PER_ENTRY, MAX_KCAL_PER_ENTRY, MAX_WATER_ML_PER_DAY } from './limits';

/*
 * Request contracts for the data API. Every schema is strict: an unknown field is an error, so a client
 * cannot slip extra keys (or MongoDB operators such as "$set") into a document. Nothing here takes an
 * identity: the owner of every document is the verified token's uid, never something in the body.
 */

const text = (max: number) => z.string().trim().max(max);
const name = (max: number) => z.string().trim().min(1).max(max);
const amount = (max: number) => z.number().min(0).max(max);

// ── users ───────────────────────────────────────────────────────────────────

/** Sent on every sign-in. Cosmetic fields only. */
export const SyncUserBody = z.strictObject({
  email: text(320).optional(),
  name: text(200).optional(),
  photo: text(2048).optional(),
  provider: text(100).optional(),
});
export type SyncUserInput = z.infer<typeof SyncUserBody>;

const Birthdate = z.strictObject({ day: text(2), month: text(2), year: text(4) });

/** What the onboarding form collects. Replaced as a whole when saved. */
export const PhysicalProfile = z.strictObject({
  gender: text(50),
  goal: text(100),
  activityLevel: text(100),
  birthdate: Birthdate,
  heightFeet: text(4),
  heightInches: text(4),
  weightKg: text(8),
});

/** Merged field by field, so editing the goal never wipes the name. */
const UserProfilePatch = z.strictObject({
  name: text(200).optional(),
  goal: text(200).optional(),
  activityLevel: text(200).optional(),
  coachType: text(200).optional(),
  dietType: text(200).optional(),
});

/** The user's daily targets. Also merged field by field. */
const GeneratedPlanPatch = z.strictObject({
  dailyCalories: z.number().min(100).max(20_000).optional(),
  macros: z
    .strictObject({
      carbs: text(16).optional(),
      protein: text(16).optional(),
      fats: text(16).optional(),
    })
    .optional(),
  waterIntake: text(16).optional(),
  planSummary: text(2_000).optional(),
  fitnessTips: z.array(text(300)).max(20).optional(),
});

export const UserPatchBody = z
  .strictObject({
    physicalProfile: PhysicalProfile.optional(),
    userProfile: UserProfilePatch.optional(),
    generatedPlan: GeneratedPlanPatch.optional(),
    onboardingCompleted: z.boolean().optional(),
    isSetupCompleted: z.boolean().optional(),
    generatedPlanStale: z.boolean().optional(),
    imageUrl: text(2048).optional(),
  })
  .refine((body) => Object.values(body).some((value) => value !== undefined), { message: 'The patch is empty.' });
export type UserPatchInput = z.infer<typeof UserPatchBody>;

// ── daily logs ──────────────────────────────────────────────────────────────

export const EXERCISE_TYPES = ['exercise', 'cardio', 'weight', 'manual'] as const;

/** `itemId` is the food's or dish's own id from the app's datasets. The entry gets its own unique id server-side. */
const common = {
  itemId: text(200).optional(),
  name: name(500),
  time: text(40).optional(),
};

const FoodEntry = z.strictObject({
  ...common,
  type: z.literal('food'),
  calories: amount(MAX_KCAL_PER_ENTRY),
  carbs: amount(MAX_GRAMS_PER_ENTRY).optional(),
  protein: amount(MAX_GRAMS_PER_ENTRY).optional(),
  fat: amount(MAX_GRAMS_PER_ENTRY).optional(),
  fiber: amount(MAX_GRAMS_PER_ENTRY).optional(),
  servingSize: text(200).optional(),
  amount: text(200).optional(),
});

const ExerciseEntry = z.strictObject({
  ...common,
  type: z.enum(EXERCISE_TYPES),
  calories: amount(MAX_KCAL_PER_ENTRY),
  duration: amount(MAX_DURATION_MIN).optional(),
  intensity: text(100).optional(),
});

const WaterEntry = z.strictObject({
  ...common,
  type: z.literal('water'),
  amountMl: z.number().min(1).max(MAX_WATER_ML_PER_DAY),
  amount: text(40).optional(),
});

export const EntryBody = z.discriminatedUnion('type', [FoodEntry, ExerciseEntry, WaterEntry]);
export type EntryInput = z.infer<typeof EntryBody>;

export const DateId = z.string().refine(isValidDateId, { message: 'Not a calendar date (YYYY-MM-DD).' });

export const ListQuery = z.strictObject({
  from: DateId.optional(),
  to: DateId.optional(),
  limit: z.coerce.number().int().min(1).max(366).default(31),
});
export type ListQueryInput = z.infer<typeof ListQuery>;

/** Entry ids are UUIDs generated by the server. */
export const EntryId = z.string().regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
