import type { TotalField } from './limits';

// ── stored documents (MongoDB) ──────────────────────────────────────────────

export type EntryType = 'food' | 'exercise' | 'cardio' | 'weight' | 'manual' | 'water';

/** One line in a day's log. Everything needed to take its effect back out of the totals is stored on it. */
export interface LogEntry {
  /** Unique per entry, generated by the server. */
  id: string;
  type: EntryType;
  /** The food's or dish's own id from the app's datasets (the same food can be logged twice). */
  itemId?: string;
  name: string;
  calories?: number;
  carbs?: number;
  protein?: number;
  fat?: number;
  fiber?: number;
  amountMl?: number;
  servingSize?: string;
  amount?: string;
  time?: string;
  duration?: number;
  intensity?: string;
  createdAt: Date;
}

export type DayTotals = Record<TotalField, number>;

/** One document per user per day. `uid` is always the verified token's uid. */
export interface DayDoc extends DayTotals {
  uid: string;
  date: string;
  logs: LogEntry[];
  lastUpdated: Date;
}

export interface PhysicalProfileDoc {
  gender: string;
  goal: string;
  activityLevel: string;
  birthdate: { day: string; month: string; year: string };
  heightFeet: string;
  heightInches: string;
  weightKg: string;
}

export interface UserProfileDoc {
  name?: string;
  goal?: string;
  activityLevel?: string;
  coachType?: string;
  dietType?: string;
}

export interface GeneratedPlanDoc {
  dailyCalories?: number;
  macros?: { carbs?: string; protein?: string; fats?: string };
  waterIntake?: string;
  planSummary?: string;
  fitnessTips?: string[];
}

/** One document per user; `_id` is the Firebase uid. */
export interface UserDoc {
  _id: string;
  email?: string;
  name?: string;
  photo?: string;
  provider?: string;
  imageUrl?: string;
  createdAt?: Date;
  lastLoginAt?: Date;
  lastUpdated?: Date;
  onboardingCompletedAt?: Date;
  onboardingCompleted?: boolean;
  isSetupCompleted?: boolean;
  generatedPlanStale?: boolean;
  physicalProfile?: PhysicalProfileDoc;
  userProfile?: UserProfileDoc;
  generatedPlan?: GeneratedPlanDoc;
}

// ── what the API returns (dates as ISO strings) ─────────────────────────────

export type LogEntryDto = Omit<LogEntry, 'createdAt'> & { createdAt: string };

export interface DayDto extends DayTotals {
  date: string;
  logs: LogEntryDto[];
  lastUpdated: string;
}

export type UserDto = Omit<UserDoc, '_id' | 'createdAt' | 'lastLoginAt' | 'lastUpdated' | 'onboardingCompletedAt'> & {
  id: string;
  createdAt?: string;
  lastLoginAt?: string;
  lastUpdated?: string;
  onboardingCompletedAt?: string;
};
